window.BOT_FEATURES=[
{name:"🛠️ 日常工具",title:"想到就丟給 Bot",desc:"提醒、計時、倒數、計算、單位換算、骰子、隨機選擇、密碼、翻譯、天氣、日期、QR Code 都集中在這裡。"},
{name:"🗳️ 群組互動",title:"投票不用自己數",desc:"建立單選或多選投票，大家直接用下拉選單投票，可以選擇匿名，也能設定時間到自動結束。"},
{name:"💬 自動回覆",title:"你說什麼，我照你的設定回",desc:"自己設定觸發文字與回覆內容，例如「早安」→「早安啊」。不用 AI 自己亂猜，回什麼完全由你決定。"},
{name:"🎭 身分組",title:"按一下就能拿身分組",desc:"管理員可以建立按鈕面板或下拉選單。下拉選單支援一次選多個身分組，再選一次可以取消。"},
{name:"🕹️ 小遊戲",title:"無聊就來玩一下",desc:"猜拳、猜數字、Trivia、21 點、高低、Wordle、Hangman、反應力、打字、記憶、心算、真心話、大冒險等都能直接在 Discord 玩。"},
{name:"🏆 排行榜",title:"玩久了會有紀錄",desc:"統計 XP、聊天數、語音時間、遊戲勝場與遊戲場次，提供伺服器排行榜。"},
{name:"⭐ XP／成就",title:"聊天和玩遊戲都會累積",desc:"聊天會慢慢拿 XP、升級，遊戲和語音也會留下紀錄，另外有成就進度可以慢慢解。"},
{name:"🎁 抽獎",title:"按鈕參加，到點直接抽",desc:"設定獎品、時間與得獎人數，成員按按鈕參加，時間到 Bot 自動抽獎，也能重新抽。"},
{name:"🎵 語音音樂",title:"不用找網址，直接搜尋",desc:"進入語音後輸入歌曲名稱就能讓 Bot 搜尋 YouTube。支援搜尋選歌、播放佇列、暫停、繼續、跳歌、循環、隨機、音量等。"},
{name:"🖼️ 圖片工具",title:"丟圖片就能處理",desc:"查看頭像與 Banner，也能把圖片縮放、抓平均顏色；OCR 可在設定 API Key 後使用。"},
{name:"🔎 搜尋",title:"Discord 裡直接查",desc:"可以在 Discord 搜 YouTube、Wikipedia 與 GitHub 公開專案，不用一直切到瀏覽器。"},
{name:"🤖 AI",title:"需要再開，不會硬塞",desc:"提供 AI 問答、翻譯、摘要等功能；使用前設定 OPENAI_API_KEY，Bot 會用比較像朋友聊天的語氣回覆。"},
{name:"🔊 語音",title:"除了音樂，語音也能管",desc:"可以建立臨時語音、語音進出通知、語音統計；沒人的臨時語音可以自動清掉。"},
{name:"🛡️ 管理",title:"常用管理指令集中處理",desc:"清訊息、慢速模式、鎖頻道、解鎖、警告、Timeout、Kick、Ban、Unban 與管理紀錄都整合進來。"},
{name:"🚨 防濫用",title:"大量 @ 直接攔",desc:"預設一則訊息出現 5 個以上 Mention 就會立即刪除，另外可開啟防刷、邀請連結與大量大寫字母攔截。"},
{name:"📜 Log",title:"重要操作有地方看",desc:"可以把管理事件送進指定紀錄頻道，像是警告、Timeout、Kick、Ban，以及防刷事件。"},
{name:"⚙️ 設定",title:"每個伺服器自己調",desc:"管理員可以查看設定、設定新人身分組、歡迎訊息、離開通知與其他 Bot 行為。"},
{name:"📝 個人筆記",title:"叫 Bot 幫你記東西",desc:"自己的筆記只有自己能查看，適合記一串網址、待辦、指令或臨時資料。"},
{name:"👤 個人資料",title:"自己的資料集中看",desc:"查看等級、XP、聊天數、語音時間、遊戲紀錄、成就與頭像等資料。"}
];

window.BOT_COMMANDS=[
{name:"/spam",category:"核心",title:"多頻道訊息發送",desc:"選擇多個文字頻道後發送指定內容與次數，Bot 會先檢查自己是否能在那些頻道發言。",params:"content / count",example:"/spam content:你好 count:10"},
{name:"/stopspam",category:"核心",title:"停止發送工作",desc:"停止自己正在執行的發送工作；有相應權限的人也能停止指定使用者的工作。",params:"member?",example:"/stopspam"},
{name:"/history",category:"核心",title:"歷史訊息清理",desc:"依頻道、成員或關鍵字搜尋歷史訊息，並在有管理訊息與讀取歷史權限時清掉它們。",params:"count / member? / content? / channels?",example:"/history count:100"},
{name:"/remind add",category:"日常",title:"新增提醒",desc:"例如 10m、2h、1d，到時間 Bot 會回來提醒你。",params:"after / message",example:"/remind add after:30m message:關電腦"},
{name:"/remind list",category:"日常",title:"查看提醒",desc:"列出自己目前還沒到時間的提醒。",params:"—",example:"/remind list"},
{name:"/remind cancel",category:"日常",title:"取消提醒",desc:"用提醒編號刪掉一個待處理提醒。",params:"reminder_id",example:"/remind cancel reminder_id:3"},
{name:"/timer",category:"日常",title:"計時器",desc:"倒數一段時間，結束後在目前頻道通知你。",params:"duration",example:"/timer duration:5m"},
{name:"/countdown",category:"日常",title:"短倒數",desc:"最長 1 小時的短倒數，時間到直接提醒。",params:"seconds",example:"/countdown seconds:30"},
{name:"/calc",category:"日常",title:"計算機",desc:"支援一般加減乘除、括號、百分比與次方等簡單算式。",params:"expression",example:"/calc expression:(20+5)*3"},
{name:"/convert",category:"日常",title:"單位換算",desc:"支援 km/m、m/cm、kg/g、時間與 C/F 等常用單位。",params:"value / from_unit / to_unit",example:"/convert value:5 from_unit:km to_unit:m"},
{name:"/coin",category:"日常",title:"丟硬幣",desc:"隨機出正面或反面。",params:"—",example:"/coin"},
{name:"/dice",category:"日常",title:"骰子",desc:"丟一顆自訂面數的骰子。",params:"sides",example:"/dice sides:20"},
{name:"/roll",category:"日常",title:"自訂骰子",desc:"支援像 2d20+3 的寫法，可以一次丟多顆。",params:"formula",example:"/roll formula:2d20+3"},
{name:"/choose",category:"日常",title:"隨機選擇",desc:"用逗號分隔選項，Bot 幫你隨機挑一個。",params:"options",example:"/choose options:A,B,C"},
{name:"/password",category:"日常",title:"密碼產生器",desc:"在私密回覆中產生隨機密碼，避免直接把密碼丟在公開頻道。",params:"length",example:"/password length:20"},
{name:"/translate",category:"日常",title:"翻譯",desc:"把一句話自動翻成指定語言。",params:"text / target",example:"/translate text:Hello target:zh-TW"},
{name:"/weather",category:"日常",title:"天氣",desc:"查指定城市目前的溫度、體感與濕度。",params:"city",example:"/weather city:Changhua"},
{name:"/age",category:"日常",title:"年齡計算",desc:"輸入生日，直接算目前幾歲。",params:"birthday",example:"/age birthday:2010-08-20"},
{name:"/days",category:"日常",title:"日期相差",desc:"算兩個日期之間差幾天。",params:"start / end",example:"/days start:2026-09-01 end:2026-09-27"},
{name:"/qr",category:"日常",title:"QR Code",desc:"把網址或文字做成圖片 QR Code。",params:"text",example:"/qr text:https://example.com"},
{name:"/time",category:"日常",title:"台灣時間",desc:"快速查看台灣目前時間。",params:"—",example:"/time"},
{name:"/poll create",category:"群組",title:"建立投票",desc:"建立 2～10 個選項的投票，可單選、多選、匿名，也可以設定結束時間。",params:"question / options / multiple / anonymous / minutes",example:"/poll create question:今晚玩什麼 options:Minecraft,Roblox,Valorant"},
{name:"/poll end",category:"群組",title:"提前結束投票",desc:"管理員可以直接結束一個還在進行的投票。",params:"poll_id",example:"/poll end poll_id:12"},
{name:"/autoreply add",category:"自動化",title:"新增自動回覆",desc:"自己決定觸發文字與 Bot 回覆內容，可選擇完全匹配或包含關鍵字。",params:"trigger / response / exact",example:"/autoreply add trigger:早安 response:早安啊！"},
{name:"/autoreply edit",category:"自動化",title:"修改自動回覆",desc:"修改既有規則的觸發內容或回覆。",params:"rule_id / trigger? / response? / exact?",example:"/autoreply edit rule_id:1 response:午安"},
{name:"/autoreply list",category:"自動化",title:"查看自動回覆",desc:"列出目前伺服器設定的自動回覆規則。",params:"—",example:"/autoreply list"},
{name:"/autoreply remove",category:"自動化",title:"刪除自動回覆",desc:"用編號刪掉一組不需要的自動回覆。",params:"rule_id",example:"/autoreply remove rule_id:1"},
{name:"/rolepanel create",category:"身分組",title:"建立領取面板",desc:"做出按鈕或下拉選單面板。下拉選單可以一次選多個身分組。",params:"title / description / mode / roles",example:"/rolepanel create title:選你的遊戲 description:自己選 mode:下拉選單"},
{name:"/rolepanel list",category:"身分組",title:"查看面板",desc:"看看這個伺服器已經建立了哪些身分組面板。",params:"—",example:"/rolepanel list"},
{name:"/rolepanel delete",category:"身分組",title:"刪除面板",desc:"移除指定身分組面板與它的 Bot 紀錄。",params:"panel_id",example:"/rolepanel delete panel_id:2"},
{name:"/game",category:"遊戲",title:"小遊戲中心",desc:"下面的遊戲都從 /game 進入。",params:"rps / guess / trivia / blackjack / higherlower / wordle / hangman / reaction / typing / memory / math / 8ball / truth / dare / wouldyourather / neverhaveiever",example:"/game rps choice:剪刀"},
{name:"/leaderboard",category:"成長",title:"群組排行榜",desc:"依 XP、聊天、語音時間、遊戲勝場或遊戲場次排序。",params:"kind?",example:"/leaderboard kind:XP"},
{name:"/profile",category:"成長",title:"個人資料",desc:"顯示等級、XP、聊天、語音與遊戲紀錄。",params:"member?",example:"/profile"},
{name:"/achievements",category:"成長",title:"成就",desc:"查看已解鎖與還沒解鎖的成就。",params:"—",example:"/achievements"},
{name:"/giveaway create",category:"活動",title:"建立抽獎",desc:"設定獎品、倒數時間與得獎人數，成員按鈕參加。",params:"prize / duration / winners",example:"/giveaway create prize:遊戲點數 duration:1h winners:2"},
{name:"/giveaway end",category:"活動",title:"結束抽獎",desc:"管理員可以提前結束並抽出得獎者。",params:"giveaway_id",example:"/giveaway end giveaway_id:3"},
{name:"/giveaway reroll",category:"活動",title:"重新抽獎",desc:"對已經有參加名單的抽獎重新抽人。",params:"giveaway_id",example:"/giveaway reroll giveaway_id:3"},
{name:"/music search",category:"音樂",title:"搜尋歌曲",desc:"直接搜 YouTube，顯示結果後點按鈕選歌。",params:"query",example:"/music search query:夜空中最亮的星"},
{name:"/music play",category:"音樂",title:"搜尋並播放",desc:"輸入歌名後會先列出搜尋結果，點選你要的歌曲才開始播放。",params:"query",example:"/music play query:YOASOBI アイドル"},
{name:"/music queue",category:"音樂",title:"播放佇列",desc:"查看正在播放與後面排隊的歌曲。",params:"—",example:"/music queue"},
{name:"/music nowplaying",category:"音樂",title:"現在播放",desc:"查看目前正在播的歌曲與循環狀態。",params:"—",example:"/music nowplaying"},
{name:"/music pause",category:"音樂",title:"暫停",desc:"暫停現在的歌曲。",params:"—",example:"/music pause"},
{name:"/music resume",category:"音樂",title:"繼續",desc:"把剛剛暫停的歌曲繼續播。",params:"—",example:"/music resume"},
{name:"/music skip",category:"音樂",title:"下一首",desc:"跳過目前歌曲。",params:"—",example:"/music skip"},
{name:"/music volume",category:"音樂",title:"音量",desc:"把播放音量調成 0～100。",params:"value",example:"/music volume value:70"},
{name:"/music shuffle",category:"音樂",title:"隨機播放",desc:"把等待中的佇列打亂。",params:"—",example:"/music shuffle"},
{name:"/music loop",category:"音樂",title:"循環模式",desc:"切換關閉、單曲或整個佇列循環。",params:"—",example:"/music loop"},
{name:"/music remove",category:"音樂",title:"移除歌曲",desc:"從佇列移除指定編號。",params:"index",example:"/music remove index:2"},
{name:"/music clear",category:"音樂",title:"清空佇列",desc:"清掉等待中的歌曲，但不會影響目前正在播放的那首。",params:"—",example:"/music clear"},
{name:"/music leave",category:"音樂",title:"離開語音",desc:"停止音樂並讓 Bot 離開語音頻道。",params:"—",example:"/music leave"},
{name:"/avatar",category:"圖片",title:"查看頭像",desc:"查看自己或其他成員的高清頭像。",params:"member?",example:"/avatar"},
{name:"/banner",category:"圖片",title:"查看 Banner",desc:"查看成員目前的 Discord Banner。",params:"member?",example:"/banner"},
{name:"/userinfo",category:"圖片",title:"使用者資訊",desc:"查看 ID、加入時間與身分組。",params:"member?",example:"/userinfo"},
{name:"/serverinfo",category:"圖片",title:"伺服器資訊",desc:"查看成員、頻道、身分組與建立時間。",params:"—",example:"/serverinfo"},
{name:"/membercount",category:"圖片",title:"成員數量",desc:"快速查看目前伺服器成員數。",params:"—",example:"/membercount"},
{name:"/image resize",category:"圖片",title:"圖片縮放",desc:"丟圖進來指定寬度，Bot 會幫你縮放並回傳 PNG。",params:"image / width",example:"/image resize width:800"},
{name:"/image color",category:"圖片",title:"平均顏色",desc:"抓圖片的大致平均 RGB 顏色並轉成 HEX。",params:"image",example:"/image color"},
{name:"/image ocr",category:"圖片",title:"OCR 文字辨識",desc:"需要 OCR_SPACE_API_KEY，設定後可以從圖片抓文字。",params:"image",example:"/image ocr"},
{name:"/search youtube",category:"搜尋",title:"YouTube 搜尋",desc:"在 Discord 裡直接找影片。",params:"query",example:"/search youtube query:Discord Bot"},
{name:"/search wikipedia",category:"搜尋",title:"Wikipedia 搜尋",desc:"搜尋中文 Wikipedia 並列出結果連結。",params:"query",example:"/search wikipedia query:Roblox"},
{name:"/search github",category:"搜尋",title:"GitHub 搜尋",desc:"搜尋 GitHub 上的公開專案。",params:"query",example:"/search github query:discord bot python"},
{name:"/ai ask",category:"AI",title:"AI 問答",desc:"設定 OPENAI_API_KEY 後使用；短回答直接顯示，太長會自動變成可直接開啟的文字檔。",params:"prompt",example:"/ai ask prompt:幫我想晚餐吃什麼"},
{name:"/ai translate",category:"AI",title:"AI 翻譯",desc:"需要 OPENAI_API_KEY，把文字翻成指定語言並順一下語氣。",params:"text / target",example:"/ai translate text:Hello target:繁體中文"},
{name:"/ai summarize",category:"AI",title:"AI 摘要",desc:"需要 OPENAI_API_KEY，把一段長文字濃縮成容易看的重點。",params:"text",example:"/ai summarize text:這是一大段文字"},
{name:"/voice temp",category:"語音",title:"臨時語音",desc:"先進語音，再執行這個指令，Bot 會幫你建一個沒人就會刪掉的臨時語音。",params:"name?",example:"/voice temp name:開黑"},
{name:"/voice notice",category:"語音",title:"語音進出通知",desc:"把成員進出語音的通知送到指定文字頻道。",params:"channel",example:"/voice notice channel:#語音通知"},
{name:"/voice noticeoff",category:"語音",title:"關閉語音通知",desc:"停止語音進出通知。",params:"—",example:"/voice noticeoff"},
{name:"/voice stats",category:"語音",title:"語音統計",desc:"看看自己累積待過語音多久。",params:"—",example:"/voice stats"},
{name:"/clear",category:"管理",title:"清除訊息",desc:"刪除目前文字頻道最近 1～100 則訊息。",params:"amount",example:"/clear amount:20"},
{name:"/slowmode",category:"管理",title:"慢速模式",desc:"設定目前頻道慢速模式秒數，0 代表關閉。",params:"seconds",example:"/slowmode seconds:5"},
{name:"/lock",category:"管理",title:"鎖頻道",desc:"暫時禁止一般成員在目前頻道發言。",params:"—",example:"/lock"},
{name:"/unlock",category:"管理",title:"解除鎖定",desc:"恢復一般成員在目前頻道的發言權。",params:"—",example:"/unlock"},
{name:"/warn",category:"管理",title:"成員警告",desc:"留下警告紀錄，但不會直接把成員踢出。",params:"member / reason",example:"/warn member:@某人 reason:洗版"},
{name:"/warnings",category:"管理",title:"查看警告",desc:"查看指定成員過去的警告紀錄。",params:"member",example:"/warnings member:@某人"},
{name:"/timeout",category:"管理",title:"Timeout",desc:"暫時限制成員聊天。",params:"member / minutes / reason",example:"/timeout member:@某人 minutes:10"},
{name:"/kick",category:"管理",title:"Kick",desc:"把成員踢出伺服器。",params:"member / reason",example:"/kick member:@某人 reason:洗版"},
{name:"/ban",category:"管理",title:"Ban",desc:"封鎖並踢出成員。",params:"member / reason",example:"/ban member:@某人 reason:違規"},
{name:"/unban",category:"管理",title:"Unban",desc:"用 Discord 使用者 ID 解除封鎖。",params:"user_id",example:"/unban user_id:123456789"},
{name:"/security mention-limit",category:"安全",title:"Mention 上限",desc:"預設 5 個 Mention 就攔截；可改成其他數字或關閉限制。",params:"limit",example:"/security mention-limit limit:5"},
{name:"/security antispam",category:"安全",title:"防刷",desc:"6 秒內發太多訊息時會自動攔截，門檻可調。",params:"enabled / limit",example:"/security antispam enabled:true limit:8"},
{name:"/security invites",category:"安全",title:"邀請連結防護",desc:"開啟後 Discord 邀請連結會被 Bot 自動攔截。",params:"enabled",example:"/security invites enabled:true"},
{name:"/security caps",category:"安全",title:"大寫刷屏防護",desc:"大量連續大寫字母的訊息可以直接攔。",params:"enabled",example:"/security caps enabled:true"},
{name:"/modlog set",category:"安全",title:"設定管理紀錄頻道",desc:"把管理與防刷事件送到指定頻道。",params:"channel",example:"/modlog set channel:#bot-logs"},
{name:"/modlog disable",category:"安全",title:"關閉管理紀錄",desc:"停止把管理紀錄發到文字頻道。",params:"—",example:"/modlog disable"},
{name:"/settings show",category:"設定",title:"查看伺服器設定",desc:"一次查看防刷、Mention、Log、歡迎、離開、語音通知與新人身分組等設定。",params:"—",example:"/settings show"},
{name:"/settings autorole",category:"設定",title:"新人自動身分組",desc:"新人加入後自動拿到指定身分組。",params:"role?",example:"/settings autorole role:@新人"},
{name:"/settings welcome",category:"設定",title:"新人歡迎",desc:"設定新人加入時要在哪個頻道說什麼，可用 {user} 與 {server}。",params:"channel? / message?",example:"/settings welcome channel:#歡迎"},
{name:"/settings goodbye",category:"設定",title:"離開通知",desc:"設定成員離開時要在哪個頻道說什麼。",params:"channel? / message?",example:"/settings goodbye channel:#離開"},
{name:"/note add",category:"設定",title:"新增個人筆記",desc:"把小東西存給自己，其他人看不到。",params:"title / content",example:"/note add title:網址 content:https://example.com"},
{name:"/note list",category:"設定",title:"筆記列表",desc:"查看自己保存過哪些筆記。",params:"—",example:"/note list"},
{name:"/note show",category:"設定",title:"查看筆記",desc:"用編號打開一篇自己的筆記。",params:"note_id",example:"/note show note_id:2"},
{name:"/note delete",category:"設定",title:"刪除筆記",desc:"刪掉指定編號的個人筆記。",params:"note_id",example:"/note delete note_id:2"}
];
